### ISSUE TITLE
How do I docktitude?

### ISSUE THREAD

**Issue by monkpit** [docktitude/docktitude#1]
This tool looks like it might help me, but I'm not sure how to use it. I'm not even sure where to get the binary so that I can start trying to figure it out myself.

Could you modify your documentation to include a minimal example (not pseudocode), and include a link to the binary release? This repo contains a demo folder - could you write up how to make docktitude "go" using the demo folder as an example?

I have read your entire webpage / readme a few times over, and I'm not sure what exactly is going on. I'll be the first to admit, I'm a docker noob for sure - but through some googling I ended up at this site, because creating and managing a "docker images hierarchy" sounds exactly like what I need for my use case.

**Comment by luminapps-zz** [comment]
@monkpit A new version has been released. You can now easily install Docktitude via npm (the package manager for node.js). Simply run 'npm install -g docktitude'.
The previous version is still available in the releases part (https://github.com/docktitude/docktitude/releases).

The demo folder has for main purpose the tree demonstration (config, info too). Once docktitude has been installed, 'cd demo/docker-contexts' then run 'docktitude tree' in order to see the docker images hierarchy as a tree-like format. This folder only contains minimal Dockerfile declarations for this purpose.
